name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with: 
        version: 'v10'
        cred: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        azcopy --version | grep 'azcopy'
        touch testfile
        azcopy copy ./testfile https://$AZCOPY_TEST_STORAGE.blob.core.windows.net/$AZCOPY_TEST_CONTAINER/$AZCOPY_TEST_BLOB_DEST --overwrite=true
      env:
        AZCOPY_TEST_STORAGE: "installazcopyactiontest"
        AZCOPY_TEST_CONTAINER: "githubflow"
        AZCOPY_TEST_BLOB_DEST: "testfile"
